Bugfix: support filtering out only some of the partitions (#863)
* Reproduce failures when filtering partitions

PostgreSQL command `TRUNCATE ONLY` does not support partitioned tables.
This commit adds a test case to ensure that the `TRUNCATE ONLY` command
is not used on partitioned tables.

ERROR:  cannot truncate only a partitioned table
HINT:  Do not specify the ONLY keyword, or use TRUNCATE ONLY on the partitions directly.
ERROR:  cannot truncate only a partitioned table
SQL query: TRUNCATE ONLY partitioned_tables.sellers

* Filter out partitioned tables when listing tables

* Fix tests